name: Publish

on:
  push:
    branches: [ master ]
  # Run every hour
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v6
      with:
        python-version: '3.10'
    - uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install requirements
      run: |
        pip install -r requirements.txt
    - uses: actions/cache@v4
      with:
        path: cache/
        key: ${{ runner.os }}-pip-${{ hashFiles('**/generate_rss.py') }}
        restore-keys: |
          ${{ runner.os }}-rss-
    - run: python generate_rss.py
    - name: Setup Pages
      uses: actions/configure-pages@v5
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'output'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4